- actions/addContract.ts
- actions/checkForAndPlaceOrder.ts
- actions/model.ts
- actions/utils.spec.ts
- actions/utils.ts
**Overview**
This PR:
1. Fixes a model breakage in PR #10.
2. Applies nits for variable / constant nomenclature.
**Related Issues:**
On merge, this PR:
1. Closes #12 
2. Closes #13
> fix: model breakage and nomenclature

- .env.example
- actions/checkForAndPlaceOrder.ts
- actions/checkForSettlement.ts
- actions/model.ts
- actions/test/run_local.ts
- actions/utils/poll.ts
This PR makes some small improvements, in principle not very related, but to keep things simpler, i prefer to do in a single PR
The conditional orders have a `toString` implementation that would show in plain English the order details. This is super handy to understand any issues with the Polling Logic that come after:
> ⚠️ This change modifies the model, however the change is backwards compatible
I added the `pollResult` to the conditional order, with the latest poll result.
Although this PR is backward compatible with the model, a future PR might not be. 
This is why I want to introduce in this PR some versioning on the conditional order model.
The key is the revived function, it will receive the current version that needs to be parsed. It's expected that the function will parse the …
> Misc: Persist polling result, poll latest block, versioning support

- actions/checkForAndPlaceOrder.ts
- actions/model.ts
This PR aims to reduce the noise on errors happening during the polling of conditional orders.
A good default handling is to return `TRY_NEXT_BLOCK` for the errors:
* InsufficientBalance,
* InsufficientAllowance,
* InsufficientFee
These errors are handled since we don't want to consider this as an error, and retrying in next block might give a different result.
In the future, we can do some better error handling by delegating to the SDK (the SDK can use the API, and also delegate to child orders)
This PR turns green DEV environment:
> Handle some API errors

- actions/checkForAndPlaceOrder.ts
- actions/package.json
- actions/test/run_local.ts
- actions/utils/context.ts
- actions/utils/logging.ts
Test to log into a different tool: Loggly
They index the logs, which is nice, because they will identify for example the parameters from the order:
this PR adds also some tags to facilitate the filtering. 
We can filter by the tenderly operation, for example `addContract`, but also by chain `chain_100`:
We can filter by the values of specific  fields, and they show the different values they have for the field, for example, here we can actually see how many errors we get from the API and which type:
We can easily filter by owner for example too:
For now, I'm in the 30 days trial period, but when is over, we will need to pay for the usage
If we log over 1GB a day is super expensive. This is easy to supus given we are verbose and we index block for 3 chains. 
This PR includes a flag we can …
> Add loggly

- actions/checkForAndPlaceOrder.ts
- actions/model.ts
This PR lets watchtower to ignore the check of some conditional orders for certain conditions. 
It will use the persisted result from last poll, where we can see if:
- `TRY_AT_EPOCH`: skip the check if the epoch is not due yet
- `TRY_ON_BLOCK`: skip the check if the block number is not due yet
Fixes #8
> Don't check if its not due yet

- actions/checkForAndPlaceOrder.ts
The watch tower has in production had timeout issues with storage. Therefore, storage should be assumed to be super expensive to call / retrieve, so we should minimise the amount of state that we are storing.
If an owner no longer has any conditional orders being monitored - remove them from the registry.
Using PR #29 run a local store rebuild and observe that the end state returned does not contain any owners with no orders.
Closes #30
> Optimise stored state

- README.md
- actions/checkForAndPlaceOrder.ts
- actions/model.ts
- actions/test/run_local.ts
Given the issues that have been identified in production around the Tenderly Watch Tower, it has become a necessity to inspect / audit the watch tower's state for quality assurance / resilience testing purposes.
The `run_local` was updated with the following functionality:
Follow the instructions in the `README.md` supplement for how to rebuild the state.
Closes #28
> feat: state rebuilder

- .env.example
- README.md
- actions/addContract.ts
- actions/checkForAndPlaceOrder.ts
- actions/test/run_local.ts
- actions/utils/poll.ts
- tenderly.yaml
After reviewing the logs, and the cases pointed out by @mfw78 on unindexed order I created this PR to:
- Improve logging
- Make it easier to re-process an order for a given TX
Handled errors are not errors :) 
So for example, if the order is already orderbook and we just need to wait, is not an error. So i reduced to WARN those messages.
This hopefully will let us filter the errors in the day and reduce the noise.
See https://github.com/cowprotocol/tenderly-watch-tower/pull/32/files#diff-8e2dc90f4a6ebdf01f8603707f37f7794972fdf1827102bfce89497804f72837R185
Now you can easily debug cases of TX that create orders by adding the TX hash in the `.env`
This is way faster for debugging cases, since processing a whole block is very slow (process 100-200tx!) …
> Allow to index single tx and improve logs

- actions/utils/context.ts
This PR tries to eliminate this error 
Now we will not log anything if sentry is not set
> Dont require sentry

- actions/checkForAndPlaceOrder.ts
- actions/utils/poll.ts
While debugging, i realised it was hard to follow and filter all the logs relatively to a single order. 
As we can see here, some logs refer to some internal reference, but not all logs include it:
In this case, its hard for me to say if the API call is for that specific order.
Printing all the static input or the TX in each log is too verbose. This is why we give the order on each run a unique identifier:
`ownerCount.orderCount@block`
This will allow to find the order we want (by TX hash for example). After that we can filter for just that order and block easily
This is an example of an OUTPUT after the changes in this PR:
This will make it super easy to check:
- All logs from a single block: Search for `@29779465`, being 29779465 the block we want to see
- All logs regarding one …
> Add order ref to all logs

- actions/checkForAndPlaceOrder.ts
- actions/test/run_local.ts
- actions/utils/context.ts
This PR is an attempt to handle cases when the orders don't have enough balance or allowance better
Because is a run-time error, we will actually re-attempt in next block. 
This will create an error in the logs every 15seconds!
Further more, we will be consuming RPC calls, and punish the API trying to post orders that are unbacked!
This PR will handle this case, and schedule next poll only after 10 minutes (this should reduce errors and calls by `50x` and still give the user a chance to add the balance and allowance to get their order back on track)
This handling is less drastic than the alternative that would be to return a `DONT_TRY_AGAIN`.
While reviewing the logs after these cleanups, i realised the condition was flipped! so we were ignoring orders that should be checked. 
This PR …
> Schedule not balance orders + fix issue with no due orders

- package.json
- src/addContract.ts
- src/checkForAndPlaceOrder.ts
- src/modes/run.ts
- src/types/model.ts
- src/utils/context.ts
Given that now the code has contexts which change across different chains, it's important to be careful about distinguishing this.
Confirm sync still works from genesis:
```bash
docker run -v ./database:/usr/src/app/database -it watchtower run --rpc http://172.33.0.6:8545 --rpc http://172.33.0.5:8545 --deployment-block 17883049 --deployment-block 29389123 --page-size 0 --one-shot true
```
Closes #50
> refactor: context

- src/commands/dumpDb.ts
- src/commands/index.ts
- src/index.ts
- src/types/index.ts
- src/types/model.ts
This PR adds a dump-db command feature to meet the requirements for analysing inter-watch-tower performance.
1. Test with no database (confirm create keys).
2. Test with existing database (confirm loads keys correctly).
Fixes #48
> feat: `dump-db` command

- src/domain/chainContext.ts
This PR provides a main watch dog loop to both keep the block monitor running, and ensure that the chain continues to progress.
1. Run normally using `yarn ts-node ./src/index.ts run --rpc http://10.23.0.2:8545 --rpc http://10.23.0.2:8645 --deployment-block 17883049 --deployment-block 29389123 --page-size 10000`.
2. Disconnect machine from the internet / network and observe watchdog timer counts up to 30s and then exits.
Fixes #54
> feat: watchdog

- README.md
- src/commands/dumpDb.ts
- src/commands/run.ts
- src/domain/addContract.ts
- src/domain/chainContext.ts
- src/domain/checkForAndPlaceOrder.ts
- src/index.ts
- src/utils/context.ts
- src/utils/logging.ts
- src/utils/poll.ts
This PR allows to reduce the root logging level (for example to `WARN` and then raise it for specific modules
All this is done using some log level overrides defined using the env var `DEBUG`
The scope of this PR is better understood by reading the new README section on logging.
READ: https://github.com/cowprotocol/watch-tower/tree/enable-to-raise-specific-modules-log-level#logging
> feat: increase log level for specific modules

- .github/workflows/docker.yml
The auto-deploy process requires a couple of secrets that have already been configured in this repository. If we are not changing the namespace, there is no need to deploy another pod for auto-deploy as it is already deployed on the staging cluster for the `services` namespace.
The action hits the auto-deploy URL with credentials to restart all pods using the specified image.
Resolves #79
> Add auto deploy

- README.md
- package.json
- src/domain/chainContext.ts
- src/index.ts
- src/utils/logging.ts
As pointed out in this comment https://github.com/cowprotocol/infrastructure/pull/746#discussion_r1345243086, it would be simpler if we unify the ENVS that control the logging. 
Before this PR there was 2 independent env vars.
Now, everything is control with `LOG_LEVEL` env. 
To understand how to use it, refer to the README
Example:
```ini
LOG_LEVEL=WARN
```
More complex example:
```ini
LOG_LEVEL="WARN,commands=DEBUG,^checkForAndPlaceOrder=WARN,^chainContext=INFO,_checkForAndPlaceOrder:1:=INFO" yarn ts-node ./src/index.ts
```
> Merge 2 envs for logs

- package.json
- src/commands/run.ts
- src/domain/addContract.ts
- src/domain/chainContext.ts
- src/domain/checkForAndPlaceOrder.ts
- src/index.ts
- src/types/index.ts
- src/types/model.ts
- src/utils/api.ts
- src/utils/metrics.ts
- yarn.lock
This PR adds observability to the watch-tower so that it can be monitored in production.
1. Start watch-tower.
2. Check above endpoints. For `dump`, add chain Id, for example: `/api/dump/1`
Fixes #70
> feat: observability (api, metrics, and startup / liveliness probes)

- README.md
- src/commands/run.ts
- src/index.ts
- src/types/index.ts
- src/utils/api.ts
- src/utils/db.ts
- src/utils/logging.ts
This PR applies some fixes / feedback from previous PRs.
1. Run `yarn ts-node ./src/index.ts run --rpc http://10.23.0.2:8545 --rpc http://10.23.0.2:8645 --deployment-block 17883049 --deployment-block 29389123 --page-size 10000` and observe synchronisation.
**NOTE**: Substitute your RPCs in the above.
Related #89
> chore: api and version polish

- src/commands/run.ts
- src/domain/chainContext.ts
- src/index.ts
- src/types/index.ts
Some chains aren't created equal, so having a constant watch dog timeout for the block watcher isn't suitable.
1. Attempt to run with a non-integer option value that should be an integer. Observe failure to start.
2. Start with `--watchdog-timeout` flag set to non-default value, such as 120, and observe block watcher running with a 120s timeout.
Fixes #85
> fix: configurable watchdog timeout

- src/domain/checkForAndPlaceOrder.ts
- src/utils/contracts.ts
- src/utils/misc.ts
- src/utils/utils.spec.ts
Currently incompatible orders (where there is a low level reversion that's not expected) are *NOT* deleted. This corrects that.
1. Sync goerli from genesis and confirm no unexpected errors.
Fixes #91
> fix: drop incompatible orders

- src/domain/chainContext.ts
- src/types/model.ts
- src/utils/api.ts
- src/utils/context.ts
This PR provides overall health monitoring for the block watcher (chain contexts). This assists with Kubernetes deployment to enable health probes for automatic restarting and monitoring.
1. Start syncing chain from scratch.
2. Observe the `/health` API endpoint returns `500` status error, with JSON showing current chain context status.
3. Once in sync, observe the `/health` API endpoint returns `200` status with JSON showing the current chain status.
Fixes #70
> chore: health probe

- src/commands/index.ts
- src/commands/runMulti.ts
- src/domain/chainContext.ts
- src/index.ts
- src/types/index.ts
- src/utils/context.ts
A long requested feature has been to enable single-chain running of the watch-tower (as is currently done on CoW Protocol infrastructure).
1. Attempt to start a single chain as per instructions in the readme.
Fixes #71
> feat: single chain

- package.json
- src/domain/chainContext.ts
- src/domain/checkForAndPlaceOrder.ts
- src/index.ts
- src/types/index.ts
- yarn.lock
Allow to set your own Orderbook API URL instead of the default ones from the SDK.
This PR is a follow up on https://github.com/cowprotocol/cow-sdk/pull/177.
The motivation, is to allow to set our service IP instead of the external one, to make the connection more performant.
While testing this, i realized that in case of an error, the SDK re-attempts 10 times using exponential backoff. This makes it take too much time in case of an error. I reduced to 5 the attempts, and now it re-attempts, but it will take at most a few seconds instead of 2-3 minutes.
After this is merged, we will need to set it up (please, let me do it!) 
See
https://cowservices.slack.com/archives/C05RMJB7ZFA/p1697021044757619?thread_ts=1697007472.259279&cid=C05RMJB7ZFA
Pass the `--orderBookApi ` and make sure it uses …
> feat: add orderbook API base url

- src/domain/checkForAndPlaceOrder.ts
Reduce logs for `_placeOrder`. 
If the error is handled (we know the API error and we decide to do some handling of it, then we consider it is not an error (therefore, we reduce the logging to INFO):
For example, for `InsufficientBalance`
Context: https://cowservices.slack.com/archives/C05RMJB7ZFA/p1697458518321669
Also: https://github.com/cowprotocol/watch-tower/blob/reduce-logs/src/domain/checkForAndPlaceOrder.ts#L496
> chore: reduce logged errors

- src/utils/metrics.ts
Follow up on comments from https://github.com/cowprotocol/watch-tower/pull/102
> chore: addressed nits

- README.md
- src/commands/run.ts
- src/commands/runMulti.ts
- src/domain/chainContext.ts
- src/domain/checkForAndPlaceOrder.ts
- src/index.ts
- src/types/index.ts
This PR tweaks some configuration options for easing deployment on dappnode.
1. Follow the readme instructions for quickly running
2. Observe no errors
Fixes: #72
> chore: address filter and chain config

- src/utils/contracts.ts
There's one order in a loop of checking for every block. 
Each check, watch tower arrives to the conclusion that the order is invalid:
I can see at least 1700 attempts!
Same as we do in the SDK, we drop the invalid orders so we don't check again.
Run this in Gnosis Chain and make sure the order is properly dropped.
> fix: drop invalid orders

- src/utils/filterPolicy.ts
Closes #117 
Allows to create both DENY-LISTS, and WHITE-LISTS
For that, this PR introduces the default action, which could be: `ACCEPT`, `SKIP` or `DROP`
Now the config files are splitted by environment: `prod` and `staging`
See:
https://github.com/cowprotocol/watch-tower/tree/config
Production files have `DROP` as their default. They will whitelist all handlers in https://github.com/cowprotocol/composable-cow#deployed-contracts
Staging will default to index all orders. It will have some exceptions for orders.
```bash
LOG_LEVEL=DEBUG,checkForAndPlaceOrder=DEBUG \
yarn ts-node ./src/index.ts run \
--chain-config <RPC>,,,https://raw.githubusercontent.com/cowprotocol/watch-tower/config/prod/filter-policy-100.json \
--page-size 5000 
```
Actually, i can see if I run it with PROd config, is …
> feat: add default action for filtering

- src/domain/chainContext.ts
- src/index.ts
- src/types/index.ts
Implement basic auth for RPCs
This PR will make worse the problem we discussed about the chain config being too error prone. So Im glad of this, so we make it more obvious this needs to change (into individual params or a config file) --> out the scope
The PR adds also support for HTTP (but this should not be used in the wild internet!! just used to test and for some internal RPC that don't have HTTPS. Note that basic auth and HTTPS is a no-no!
The motivation of this PR is that GC RPC endpoint started to fail. See https://cowservices.slack.com/archives/C0361CDD1FZ/p1700845414302179
Just add user/password at the end. Credentials shared in 1password
Example:
```bash
yarn ts-node ./src/index.ts run --chain-config <rpc>,,,,https://raw.githubusercontent.com/cowprotocol/watch-tower/config/stagin …
```
> feat: add basic auth

- src/domain/checkForAndPlaceOrder.ts
- src/utils/filterOrder.ts
Reduces pressure on the API by doing some sanity checks on orders from contracts.
1. Run on staging
2. Observe no API errors for orders that are filtered
Fixes #122
> chore: sanity check orders

- src/domain/chainContext.ts
- src/index.ts
- src/types/index.ts
This PR changes to use a websockets RPC provider
1. Run in staging!
> feat: websockets rpc provider

- src/domain/chainContext.ts
Update the filter policy every hour
> chore: update filter policy hourly

- package.json
This PR fixes missing config schemas in the build.
Edit the `config.example.json` as necessary.
1. `yarn build`
2. `node ./dist/src/index.js run --config-path ./config.example.json`
3. Observe the watch-tower starts without faults.
> fix: missing config schema json in dist

- .gitignore
- README.md
- src/utils/filterPolicy.ts
This PR contains fixes for comments from #131 
1. Follow `README.md` instructions for running locally.
> chore: pr 131 comments

- src/commands/dumpDb.ts
- src/commands/run.ts
- src/domain/events/index.ts
- src/domain/index.ts
- src/domain/polling/filtering/badOrder.ts
- src/domain/polling/filtering/index.ts
- src/domain/polling/filtering/policy.ts
- src/domain/polling/index.ts
- src/domain/polling/poll.ts
- src/services/api.ts
- src/services/chain.ts
- src/services/index.ts
- src/services/storage.ts
- src/types/model.ts
- src/utils/context.ts
- src/utils/index.ts
This PR refactors legacy locations of code to more accurately reflect the area of responsibility for the respective code.
1. Verify that `yarn test` passes
2. Run from genesis on `mainnet` and verify the block watcher comes online (passes `warmUp`).
> refactor: modular architecture

- src/domain/events/index.ts
- src/domain/polling/index.ts
- src/domain/polling/poll.ts
- src/types/model.ts
Ths PR adds the conditional order ID to our mode.
As this is a breaking change, the PR also does some model migration (from version 1 to version 2).
Additionally, it adds some additional logging to print the conditional order ID which is convenient.
> Add conditional order id to our model

- config.json.example
- src/domain/polling/filtering/policy.ts
- src/domain/polling/index.ts
- src/types/config.schema.json
- src/types/types.d.ts
It's possible that we need to quickly ignore one specific order, but we don't want to neither ignore the whole handler (i.e. all TWAP orders), nor a whole user.
For this reason, I included in this PR support for creating rules to ignore or drop orders by ID. 
One way to test this is to check how, current version of watch tower shows a ton of errors and can't process blocks in Sepolia with this config:
```json
{
"networks": [
{
"name": "sepolia",
"rpc": "wss://eth-sepolia.g.alchemy.com/v2/bUZqvmR5GCbUsE1meSoBNVlN-IqQs-_r",
"deploymentBlock": 5072748,
"filterPolicy": {
"defaultAction": "DROP",
"handlers": {
"0x44569Cbd4E10dd5e97293337964Eff32d58ed352": "ACCEPT",
"0x519BA24e959E33b3B6220CA98bd353d8c2D89920": "ACCEPT",
"0x6cF1e9cA41f7611dEf408122793c358a3d11E5a5": "ACCEPT", …
```
> Allow to create filtering policy rules by conditional order id or transaction hashes

- src/services/chain.ts
Adds support again for JSON-RPC now that infrastructure has been updated and no longer has whacky state inconsistencies.
1. Configure with JSON RPC provider, confirm starts.
2. Configure with websockets provider, confirm starts.
Fixes #138
> feat: jsonrpc and websockets

- package.json
- src/domain/events/index.ts
- src/domain/polling/index.ts
- src/services/chain.ts
- src/utils/contracts.ts
- src/utils/utils.spec.ts
Removes the janky bytecode check that was being used to enforce that the contract being indexed was `ComposableCoW` compatible. This is possible given that there are exhaustive switch statements that were published for the revert messages.
1. Remove the sepolia database.
2. Restart
3. Observe new CoW AMMs :rocket:
> Drop ComposableCoW bytecode check

- src/services/chain.ts
- src/types/model.ts
This PR is an attempt to improve the first sync for watch-tower
The issue with the current model is that
1) It enter SYNC mode
2) In SYNC mode it will check all pending blocks from last processed until the tip of the blockchains
- Instead of actually processing the blocks, its just "saving" the block for processing later (its creating a sync plan)
3) Once in SYNC, it will apply the plan
- This time it will process for real the blocks
The issues we experience is becasue between 2 and 3 there's a delay and the metric of "blocks processed" goes down. Thats our main metric.
The solution is to not make a plan and process blocks as we find them instead of  waiting to be fully catched up.
I just refactored the 2 points where we do the processing of blocks (applying the plan, and when watching …
> feat: improve first sync

- src/services/chain.ts
I found the issue here.
It was just a bad parameter for prometheus metric
Now is good, see:
https://cowservices.slack.com/archives/C0361CDD1FZ/p1719303401299659
Run this locally and observe `watch_tower_block_height` metric exposed in http://localhost:8080/metrics
> fix: fix issue with broken metric

- Dockerfile
- package.json
- src/services/chain.ts
- src/types/config.schema.json
- src/types/types.d.ts
This PR adds a new optional config parameter to each network, allowing us to define some block throttling. 
the setting is called `processEveryNumBlocks` : 
* Throttle block processing to only process blocks every N blocks. Set to 1 to process every block, 2 to process every other block, etc.
Also, note that even if we skip a block, it doesn't mean we don't have any work on it. We still need to check if there's new orders coming in. So what is actually skipped is only the programmatic order checks and posting orders. 
Also, it persists all Prometheus metrics, so it should count as a "consumed block" for our consumption rate alerts, meaning we should see the block consumption rate progressing faster. 
This is an example on how to use it: `"processEveryNumBlocks": 40,`
This would do polling …
> Throttle block consumption

- src/domain/polling/index.ts
- src/services/chain.ts
- src/services/storage.ts
- src/types/model.ts
- src/types/types.d.ts
This PR introduces more often saving of orders after processing.
For now, after every 20 orders processed, it'll trigger a db save.
There are also some logging improvements to make debugging easier.
Run the service.
It should start and process orders as usual.
There have been performance issues which I'm not able to tell what's causing it so far.
This change is an attempt to alleviate the in memory load by saving it more often.
> fix: save orders more often

- src/domain/polling/index.ts
Change on https://github.com/cowprotocol/watch-tower/pull/159 didn't go as planned
It's saving way too often.
Temporarily disabling to stop the current crashloop on staging.
The change above cause increased memory and cpu usage https://g-0263500beb.grafana-workspace.eu-central-1.amazonaws.com/goto/P6O6S2kHR?orgId=1
> chore: temporarily disable registry writting on chunks

- src/domain/polling/index.ts
- src/services/chain.ts
- src/types/model.ts
I noticed that since my last changes #159 and #160 , there has been a very visible memory leak, specially on arb1.
[graph link](https://g-0263500beb.grafana-workspace.eu-central-1.amazonaws.com/goto/sjeXFwkHg?orgId=1)
While I have not been able to detect where the memory leak is, this PR has several improvements that might help.
Run it locally: should work
~I'll also run it on staging for awhile before taking this PR out of draft.~ can't apply it, pulumi is not happy with me.
> fix: attempt to fix memory leak

- README.md
- package.json
- yarn.lock
Add Base network support
1. Use the following config:
```
{
"networks": [
{
"name": "base",
"rpc": "<set a base rpc here>",
"deploymentBlock": 21794150,
"processEveryNumBlocks": 5,
"pageSize": 5000,
"filterPolicy": {
"defaultAction": "ACCEPT",
"conditionalOrderIds": {},
"transactions": {},
"handlers": {},
"owners": {}
}
}
]
}
```
2. Run it with `yarn cli`
* Should start and process blocks accordingly
Note: Not yet able to place TWAP orders, so can't be fully tested yet
> feat: add base

- config.json.example
When running with the example configuration file, you get the following error:
```
Error parsing configuration file: SyntaxError: Expected double-quoted property name in JSON at position 387 (line 11 column 17)
at JSON.parse (<anonymous>)
at validateJSON (/usr/src/app/dist/src/index.js:122:27)
at Command.<anonymous> (/usr/src/app/dist/src/index.js:65:24)
at Command.listener [as _actionHandler] (/usr/src/app/node_modules/commander/lib/command.js:482:17)
at /usr/src/app/node_modules/commander/lib/command.js:1300:65
at Command._chainOrCall (/usr/src/app/node_modules/commander/lib/command.js:1197:12)
at Command._parseCommand (/usr/src/app/node_modules/commander/lib/command.js:1300:27)
at /usr/src/app/node_modules/commander/lib/command.js:1081:27
at Command._chainOrCall …
```
> Fix Example Configuration File

- src/services/chain.ts
@elena-zh create a TWAP tx that didn't get index in watch tower.
https://basescan.org/tx/0xa9e88af5dee1d51f217bbe7613e2897cec6b3d989e8f3cab5142aa74ccb96278#eventlog 
I saw there was not logs for that transaction. Which is odd! I can see the event for conditional order created.
During my test, my transaction was indexed. 
https://basescan.org/tx/0xf0a848e6899330e84e86160f079cf341b145b1fb2bbc2f7a8aec1dfb425384c9#eventlog 
In principle both TX emit the same event, and should have been picked in the same way, but something was making us to skip some indexing of events
I reviewed the code and saw some changes applied 2 months ago were making us skip the indexing of events for some blocks.
See:
https://github.com/cowprotocol/watch-tower/pull/161/files#r1862591918
Bring back the code that skips …
> fix: fix missing orders

- src/domain/events/index.ts
- src/services/chain.ts
- src/types/model.ts
- src/utils/misc.ts
This code doesn't change the logic, it only adds more logs and refactors the code a bit.
1. Added more logs
2. Removed excessive exports
3. Got rid of excessive ComposableCoW contract instances
4. Added "Conditional order params are equal but not the same" log
The last point is my suspect. I assume that comparation here is not valid, we should not use shallow comparison for the objects.
> chore: add more logs for OOM search

- src/types/model.ts
1. We import `import { getLogger } from "../utils";` in `types/model.ts`
2. `export * from "./model";`  is in `types/index.ts`
3. `types/index.ts` is used in `utils/misc.ts`
4. `utils/misc.ts` is exported from `"../utils"`
> fix: fix circular dependency issue

- src/domain/events/index.ts
The hypothesis works, so we can confidently add the `getAreConditionalOrderParamsEqual()` call
> fix: compare order params properly

- src/domain/polling/index.ts
This PR is the most pressing change in the proposal to improve debuggability of watch-tower described in https://docs.google.com/document/d/1rNM4pqS-d17Yx1Ei_RMMvER5vJfK1c8I7Ik74PbOHSc/edit?tab=t.0
Basically, this PR allows us to connect the discrete orders with the programmatic order that created them. This is really important, because we can connect some issues on some orders that are wrongly created by a smart contract, with the smart contract that created them in the first place.
> feat: show id of order and tx hash when posting the discrete order

- src/commands/dumpDb.ts
- src/commands/run.ts
- src/domain/events/index.ts
- src/domain/polling/index.ts
- src/domain/polling/poll.ts
- src/services/api.ts
- src/services/chain.ts
- src/services/storage.ts
- src/types/model.ts
- src/utils/context.ts
- src/utils/contracts.ts
- src/utils/logging.ts
- src/utils/utils.spec.ts
Improve logs to make them easier to debug issues. 
Logs were not great, and won't be great after this PR. The goal of this PR is to improve some aspects of the logs to make it easier to debug.
It is very useful to be able to filter by block number, or by owner, or order number. Before this PR there was some context, but this context was missing in some parts, what made things like "filtering logs per block" to not work. Now all logs include the chain id and the block number.
See example:
Additionally, it simplifies some logger names and function names, and improve some messages so they are easier to read. 
It also shows information about the number of owners and orders and how many left to process. 
The PR also makes the logger utility to receive this context raw params, so we can make …
> feat: improve log debuggability

- src/services/chain.ts
- src/utils/metrics.ts
One of the things is super hard to monitor in Watch Tower is the sync status. 
Syncing from the origin of times (deployment of composable cow), can take a while.  Currently, Its super hard to see which instances of watch-tower are in sync.
Further more, if there's a crash, or you restart a pod, it will enter in sync mode (to catch up). There could be issues of not catching up fast enough. Its very hard to see that your watch-tower is lagging behind.
Now, there's a new prometheus metric for the SYNC status.
```
watch_tower_sync_status{chain_id="1"} 0
```
Once we know we are SYNCING, its hard to tell how far we are from the tip of the blockchain. 
We have some metric to know the last indexed block, but this is hard to use to get a quick idea if we are catching up. With the block you see a …
> feat: add sync status and time from last indexed block

- src/services/chain.ts
- src/utils/metrics.ts
Follow up on https://github.com/cowprotocol/watch-tower/pull/171
This PR adds the latest mined block (tip of the chain).
It allow us to build a burn-down chart on how far we are from the chain (as we consume blocks).
This is useful to see that indeed the slope is downwards.
Otherwise, we won't arrive to the tip of the chain! 😄 
Include a new metric
```
watch_tower_block_height_latest{chain_id="1"} 21351273
```
> feat: add metric for the latest block from the chain (tip)

- src/services/chain.ts
Follow up on an error from #172 
Basically, I forgot to update the latest block after the warm up (when we are subscribing to new blocks)
I noticed, because the chart looks funny!
This PR should address the issue.
> fix: fix missing update on the latest block

- src/domain/events/index.ts
We are not respecting the filter policy in order to add or not add orders from events.
I noticed how staging indexed this an order of an owner that shouldn't have. However, in the next block got dropped because we apply the filtering using the policies at the beginning of processing a block.
This explain this increment + decreement:
You can also see this in the logs:
This pr applies the filter policy before adding an order, so we don't add it in the first place. 
You can create one TWAP using any account and see how now we don't get this increment and decrement in Grafana.
> feat: apply filter policy before adding an order

- package.json
- yarn.lock
Add Lens and BNB support for the watch tower
1. Setup lens config:
```
{
"networks": [
{
"name": "lens",
"rpc": "https://rpc.lens.xyz",
"deploymentBlock": 3516559,
"watchdogTimeout": 300,
"pageSize": 50000,
"filterPolicy": {},
"owners": {},
"transactions": {}
},
"processEveryNumBlocks": 5
}
]
}
```
2. Start service with `yarn cli run`
* Should start without issues
3. Connect https://swap-dev-git-feat-lens-bsc-cowswap-dev.vercel.app/ to a Lens Safe
4. Fund it 
5. Go to TWAP, place a TWAP order
* Order should be placed
* First order part should be created
⚠️ Orderbook MUST be deployed to prod ⚠️
> feat(new-networks): add lens and bnb support
